# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'OC-myWB' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "SDWebImage"
pod "YYModel"
pod "AFNetworking"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"


end
